go: Disable go tests due to expired certificates
The reason why I created this Flake was *exactly* because I was fed up
with various issues of either providing snakeoil certificates for every
single system in question and have generated certificates that last long
enough to not cause issues in the next few years.

That's why all the certificates generated by this Flake expire in 1000
years.

Unfortunately, it turns out that Go's crypto library did not plan for
something like this and created test certificates that last until 2025
only. Maybe they thought nobody surely isn't using Go in 2025 anymore,
but they were wrong.

Here's the test failure:

go> --- FAIL: TestVerifyConnection (0.00s)
go>     --- FAIL: TestVerifyConnection/TLSv12 (0.00s)
go>         handshake_client_test.go:1669: RequireAndVerifyClientCert-FullHandshake: handshake failed: remote error: tls: bad certificate
go>     --- FAIL: TestVerifyConnection/TLSv13 (0.00s)
go>         handshake_client_test.go:1669: RequireAndVerifyClientCert-FullHandshake: handshake failed: remote error: tls: bad certificate
go> --- FAIL: TestResumptionKeepsOCSPAndSCT (0.00s)
go>     --- FAIL: TestResumptionKeepsOCSPAndSCT/TLSv12 (0.00s)
go>         handshake_client_test.go:2460: handshake failed: remote error: tls: bad certificate
go>     --- FAIL: TestResumptionKeepsOCSPAndSCT/TLSv13 (0.00s)
go>         handshake_client_test.go:2460: handshake failed: remote error: tls: bad certificate

Instead of just disabling the specific tests, I decided to disable all
the tests because all we really care about is minica and since we're
pinning nixpkgs permanently, the build product should also be reasonably
deterministic within the architectures we support.

In addition to that, disabling the tests also brings down the overall
build time (but haven't measured by how much but also don't really
care).

Signed-off-by: aszlig <aszlig@nix.build>
Upstream issue: https://github.com/golang/go/issues/71077